# htpc-server.yml
---
- hosts: htpc
  become: yes

  vars:
      ansible_ssh_pipelining: yes
      htpc_user_username: htpc
      local_home: /home/htpc
      htpc_media_path: /media/library
  pre_tasks:

    # Copy custom/htpc.yml.sample to custom/htpc.yml
    # Update variable values
    - name: Load custom variables from htpc.yml
      include_vars: custom/htpc.yml
      failed_when: false

  roles:
    - { role: dotfiles, tags: ['r_dotfiles'], become: yes, become_user: htpc}
    - { role: dotfiles, tags: ['r_dotfiles_shulman'], become: yes, become_user: shulman, local_home:  /home/shulman}
    - { role: htpc-user }
    - { role: GR360RY.kodi-client, when: kodi_client_enabled }
    - { role: GR360RY.kodi-mysql, when: kodi_mysql_enabled }
    - { role: GR360RY.htpc-nas, when: htpc_nas_enabled }
    #- { role: htpc-server }