# htpc-server.yml
---
- hosts: htpc
  become: yes

  pre_tasks:

    # Copy custom/htpc.yml.sample to custom/htpc.yml
    # Update variable values
    - name: Load custom variables from htpc.yml
      include_vars: custom/htpc.yml
      failed_when: false

  roles:
    - { role: htpc-user }
    - { role: GR360RY.kodi-client, when: kodi_client_enabled }
    - { role: GR360RY.kodi-mysql, when: kodi_mysql_enabled }
    - { role: GR360RY.htpc-nas, when: htpc_nas_enabled }

    - { role: GR360RY.nzbtomedia, when: deluge_enabled }
    - { role: GR360RY.deluge, when: deluge_enabled }

    - { role: GR360RY.sickrage, when: sickbeard_enabled }
    - { role: GR360RY.couchpotato, when: couchpotato_enabled }
    - { role: GR360RY.htpc-manager, when: htpc_manager_enabled }

#    - { role: GR360RY.sabnzbd, when: sabnzbd_enabled }
