---
# tasks file for kodi-client

- name: Add Kodi repository
  apt_repository: repo={{ kodi_repo }} state=present update_cache=yes

- name: Make sure Kodi is installed
  apt: name='kodi' update_cache=yes cache_valid_time=3600

- name: Make sure Kodi config folders are available
  file: path={{ item }} state=directory owner={{ htpc_user_username }} group={{ htpc_user_group }} mode=0755
  with_items:
    - "~{{ htpc_user_username }}/.kodi/"
    - "~{{ htpc_user_username }}/.kodi/userdata"

- name: Update sources location
  template: src=sources.xml.j2 dest="~{{ htpc_user_username }}/.kodi/userdata/sources.xml" owner={{ htpc_user_username }} group={{ htpc_user_group }} mode=0755

- name: Update advancedsettings.xml
  template: src=advancedsettings.xml.j2 dest=~{{ htpc_user_username }}/.kodi/userdata/advancedsettings.xml owner={{ htpc_user_username }} group={{ htpc_user_group }} mode=0644

- name: Startup Kodi automatically on login in full screen mode
  template: src=kodi.desktop.j2 dest=~{{ htpc_user_username }}/.config/autostart/kodi.desktop owner={{ htpc_user_username }} group={{ htpc_user_group }} mode=0664

